# Generated by Django 3.0.2 on 2020-04-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('relase_date', models.DateField()),
                ('num_stars', models.IntegerField()),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='First_App.Musician')),
            ],
        ),
    ]
