# Generated by Django 3.0.2 on 2020-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0002_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'worst'), (2, 'bad'), (3, 'Good'), (4, 'Excelent')]),
        ),
    ]
