# Generated by Django 3.0.2 on 2020-04-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0003_auto_20200420_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
