# Generated by Django 3.0.2 on 2020-04-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('First_App', '0004_auto_20200426_1108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='Album',
        ),
    ]
